-- Anti-pattern input: one wide claim table carrying member, provider, and line data.
-- Teaching artifact only; deliberately poor. Do not deploy.
CREATE TABLE claims.claim_flat (
  claim_status STRING,
  claim_number STRING,
  member_name STRING,
  member_dob STRING,
  member_phone STRING,
  member_address STRING,
  member_gender STRING,
  claim_id STRING,
  provider_name STRING,
  provider_phone STRING,
  provider_type STRING,
  provider_city STRING,
  plan_id BIGINT,
  service_date STRING,
  diagnosis_code_1 STRING,
  diagnosis_code_2 STRING,
  diagnosis_code_3 STRING,
  line1_procedure STRING,
  line1_billed STRING,
  line2_procedure STRING,
  line2_billed STRING,
  total_billed_amount DOUBLE,
  paid_amount STRING,
  is_emergency STRING,
  attribute_name STRING,
  attribute_value STRING,
  misc STRING,
  created_timestamp TIMESTAMP,
  received_date DATE,
  CONSTRAINT pk_claim_flat PRIMARY KEY (claim_id),
  CONSTRAINT fk_claim_flat_plan FOREIGN KEY (plan_id) REFERENCES plan.health_plan (health_plan_id)
) COMMENT 'Everything about a claim in one row.';
