-- Enterprise-depth example (illustrative; not real data, not a certified model).
-- Two products at the depth the skill produces by default. Referenced products
-- (household, address, language, coverage, provider, facility, network, channel)
-- are outside this excerpt; their FK declarations show the intended wiring.

CREATE TABLE IF NOT EXISTS `__CATALOG__`.`member`.`member` (
  member_id BIGINT NOT NULL COMMENT 'Surrogate key for one insured person, stable across coverage episodes and source-system re-keys.',
  household_id BIGINT COMMENT 'Household the person currently belongs to for correspondence and family-deductible accumulation.',
  primary_address_id BIGINT COMMENT 'Current primary residential address used for service-area eligibility and mailing.',
  preferred_language_id BIGINT COMMENT 'Preferred spoken and written language for member communications and interpreter scheduling.',
  member_number STRING NOT NULL COMMENT 'Payer-issued member number printed on identification cards; unique per person and never reused.',
  source_system_code STRING COMMENT 'Code of the enrollment system of record that supplied the member, for reconciliation and lineage.',
  source_member_reference STRING COMMENT 'Member identifier in the source enrollment system, retained to reconcile re-keyed or merged records.',
  first_name STRING COMMENT 'Legal given name as recorded at enrollment; used for identity matching and correspondence.',
  middle_name STRING COMMENT 'Legal middle name or initial when supplied; optional for identity matching.',
  last_name STRING COMMENT 'Legal family name as recorded at enrollment; used for identity matching and correspondence.',
  name_suffix STRING COMMENT 'Generational or professional suffix such as JR or III, needed to separate same-name relatives.',
  birth_date DATE COMMENT 'Date of birth used for age-based rating, eligibility rules, and identity matching.',
  sex_code STRING COMMENT 'Administrative sex code captured for benefit rules that are sex-specific; governed code set.',
  marital_status_code STRING COMMENT 'Marital status code used for dependent eligibility and coordination-of-benefits checks.',
  member_type_code STRING COMMENT 'Classifies the person as subscriber, spouse, or dependent within their household coverage.',
  member_status STRING NOT NULL COMMENT 'Lifecycle state of the member record: prospective, active, suspended, terminated, or deceased.',
  member_status_reason_code STRING COMMENT 'Reason for the most recent status change, such as non-payment or loss of eligibility.',
  member_status_date DATE COMMENT 'Date the current member status took effect; drives retroactive eligibility decisions.',
  original_effective_date DATE COMMENT 'First date the person was ever covered by the payer, used for tenure and continuity rules.',
  termination_date DATE COMMENT 'Date the person ceased to have any coverage; null while any coverage remains active.',
  death_date DATE COMMENT 'Reported date of death; triggers coverage termination and claim review workflows.',
  email_address STRING COMMENT 'Preferred email address for electronic notices when the member has consented to e-delivery.',
  mobile_phone_number STRING COMMENT 'Mobile phone number in E.164 format for outreach, authentication, and text notices.',
  is_electronic_delivery_consented BOOLEAN COMMENT 'True when the member consented to receive plan documents and notices electronically.',
  is_medicare_eligible BOOLEAN COMMENT 'True when the member is entitled to Medicare, affecting coordination of benefits order.',
  has_other_coverage BOOLEAN COMMENT 'True when the member reported other health coverage requiring coordination of benefits.',
  risk_score DECIMAL(9,4) COMMENT 'Most recent prospective risk score from the approved risk model, used for care management.',
  record_version_number INT COMMENT 'Monotonic version of the member record, incremented on every material demographic change.',
  created_timestamp TIMESTAMP COMMENT 'Moment the record was first created in the lakehouse; set once at insert.',
  created_by STRING COMMENT 'Pipeline or user principal that created the record; used for audit and lineage.',
  updated_timestamp TIMESTAMP COMMENT 'Moment of the most recent change to any attribute of the record.',
  updated_by STRING COMMENT 'Pipeline or user principal that last changed the record.',
  CONSTRAINT pk_member PRIMARY KEY (member_id),
  CONSTRAINT fk_member_household FOREIGN KEY (household_id) REFERENCES `__CATALOG__`.`member`.`household` (household_id),
  CONSTRAINT fk_member_address FOREIGN KEY (primary_address_id) REFERENCES `__CATALOG__`.`location`.`address` (address_id),
  CONSTRAINT fk_member_language FOREIGN KEY (preferred_language_id) REFERENCES `__CATALOG__`.`reference`.`language` (language_id)
) USING DELTA
COMMENT 'Authoritative identity for one insured person across all coverage episodes. One row per person, independent of plan or household changes. Created at first enrollment, versioned on demographic change, and retained after termination for claims run-out and audit. Referenced by coverage, claims, care management, and correspondence. Does not hold plan elections, premiums, or provider relationships.';

CREATE TABLE IF NOT EXISTS `__CATALOG__`.`claim`.`claim` (
  claim_id BIGINT NOT NULL COMMENT 'Surrogate key for one submitted claim version as received by the payer.',
  member_id BIGINT NOT NULL COMMENT 'Insured person who received the services billed on this claim.',
  coverage_id BIGINT COMMENT 'Coverage episode matched to the service dates during eligibility verification.',
  billing_provider_id BIGINT NOT NULL COMMENT 'Provider entity that submitted the claim and receives payment.',
  rendering_provider_id BIGINT COMMENT 'Practitioner who performed the services, when different from the billing provider.',
  facility_id BIGINT COMMENT 'Facility where institutional services were delivered, for place-of-service and network checks.',
  network_id BIGINT COMMENT 'Provider network under which the claim was priced, determining in- or out-of-network benefits.',
  submission_channel_id BIGINT COMMENT 'Channel through which the claim arrived, such as clearinghouse, portal, or paper.',
  original_claim_id BIGINT COMMENT 'Claim this submission replaces or voids; null for an original submission.',
  claim_number STRING NOT NULL COMMENT 'Payer-assigned claim number shared by all versions of the same claim; format CLM-YYYY-NNNNNNNN.',
  payer_claim_control_number STRING COMMENT 'Control number returned to the submitter on acknowledgement, used in remittance and appeals.',
  patient_account_number STRING COMMENT 'Provider-assigned patient account reference echoed on remittance for provider reconciliation.',
  claim_type_code STRING NOT NULL COMMENT 'Professional, institutional, dental, or pharmacy; determines pricing and edit rules.',
  claim_frequency_code STRING COMMENT 'Original, replacement, or void indicator from the submission, governing version handling.',
  place_of_service_code STRING COMMENT 'Standard place-of-service code describing where services were delivered.',
  admission_type_code STRING COMMENT 'Urgency of an inpatient admission, used for authorization and medical review.',
  claim_status STRING NOT NULL COMMENT 'Lifecycle state: received, pended, adjudicated, paid, denied, voided, or withdrawn.',
  claim_status_reason_code STRING COMMENT 'Reason for the current status, such as missing information or duplicate submission.',
  received_timestamp TIMESTAMP NOT NULL COMMENT 'Moment the payer received the claim; starts prompt-pay timers.',
  adjudicated_timestamp TIMESTAMP COMMENT 'Moment the final adjudication decision was recorded.',
  paid_timestamp TIMESTAMP COMMENT 'Moment payment was released for the claim, when payable.',
  service_from_date DATE NOT NULL COMMENT 'First date of service on the claim, used for eligibility and benefit-period matching.',
  service_to_date DATE COMMENT 'Last date of service on the claim; equals the from date for single-day services.',
  admission_date DATE COMMENT 'Inpatient admission date for institutional claims.',
  discharge_date DATE COMMENT 'Inpatient discharge date for institutional claims.',
  prompt_pay_due_date DATE COMMENT 'Date by which payment is due under the applicable prompt-pay rule.',
  currency_code STRING NOT NULL COMMENT 'ISO 4217 currency of all amounts on the claim.',
  billed_amount DECIMAL(18,2) NOT NULL COMMENT 'Total charges submitted by the provider before pricing or edits.',
  allowed_amount DECIMAL(18,2) COMMENT 'Total amount allowed under the network contract or fee schedule after pricing.',
  member_responsibility_amount DECIMAL(18,2) COMMENT 'Deductible, copay, and coinsurance owed by the member after adjudication.',
  paid_amount DECIMAL(18,2) COMMENT 'Amount the payer paid to the provider, net of adjustments.',
  interest_amount DECIMAL(18,2) COMMENT 'Late-payment interest owed under prompt-pay rules, when payment exceeded the due date.',
  line_count INT COMMENT 'Number of service lines received on the claim, used to reconcile line-level loads.',
  processing_days INT COMMENT 'Calendar days from receipt to final adjudication, for prompt-pay and service-level reporting.',
  is_emergency BOOLEAN COMMENT 'True when the provider indicated emergency services, affecting authorization and network rules.',
  is_accident_related BOOLEAN COMMENT 'True when services relate to an accident, triggering subrogation review.',
  is_clean_claim BOOLEAN COMMENT 'True when the claim required no additional information to adjudicate, per prompt-pay rules.',
  source_system_code STRING COMMENT 'Code of the claims intake system of record, for reconciliation and lineage.',
  created_timestamp TIMESTAMP COMMENT 'Moment the record was first created in the lakehouse; set once at insert.',
  created_by STRING COMMENT 'Pipeline or user principal that created the record; used for audit and lineage.',
  updated_timestamp TIMESTAMP COMMENT 'Moment of the most recent change to any attribute of the record.',
  updated_by STRING COMMENT 'Pipeline or user principal that last changed the record.',
  CONSTRAINT pk_claim PRIMARY KEY (claim_id),
  CONSTRAINT fk_claim_member FOREIGN KEY (member_id) REFERENCES `__CATALOG__`.`member`.`member` (member_id),
  CONSTRAINT fk_claim_coverage FOREIGN KEY (coverage_id) REFERENCES `__CATALOG__`.`enrollment`.`coverage` (coverage_id),
  CONSTRAINT fk_claim_billing_provider FOREIGN KEY (billing_provider_id) REFERENCES `__CATALOG__`.`provider`.`provider` (provider_id),
  CONSTRAINT fk_claim_rendering_provider FOREIGN KEY (rendering_provider_id) REFERENCES `__CATALOG__`.`provider`.`provider` (provider_id),
  CONSTRAINT fk_claim_facility FOREIGN KEY (facility_id) REFERENCES `__CATALOG__`.`provider`.`facility` (facility_id),
  CONSTRAINT fk_claim_network FOREIGN KEY (network_id) REFERENCES `__CATALOG__`.`network`.`network` (network_id),
  CONSTRAINT fk_claim_channel FOREIGN KEY (submission_channel_id) REFERENCES `__CATALOG__`.`reference`.`submission_channel` (submission_channel_id),
  CONSTRAINT fk_claim_original FOREIGN KEY (original_claim_id) REFERENCES `__CATALOG__`.`claim`.`claim` (claim_id)
) USING DELTA
COMMENT 'One submitted claim version received from a provider for services to one member. A replacement or void creates a new row linked through original_claim_id, so history is never overwritten. Lifecycle runs from receipt through adjudication to payment or denial. Consumed by payment, remittance, appeals, prompt-pay reporting, and cost analytics. Service lines and diagnoses are child products; pricing detail and payments are separate grains.';
